### ISSUE TITLE
Example, please..

### ISSUE THREAD

**Issue by vwal** [dave-irvine/node-hapi-raml#1]
Is this supposed to be functional at the moment? How do I get lib from the src.. renaming the dir doesn't seem to work; with node 4.1.1 I get:

	import fs from 'fs';
	^^^^^^
	
	SyntaxError: Unexpected reserved word

A minimal example would be awesome; this looks such a cool idea, if it works..

**Comment by dave-irvine** [comment]
Hi,

Sorry I completely missed that you posted an issue (thanks Github!).

You need to build the src to lib. This should have happened after you installed this from npm. Or did you just clone from Github?

If you run `npm run build`, you should get a `lib` directory.

But yes this lib needs a full example.

**Comment by dave-irvine** [comment]
Hi @vwal,

I added an example in https://github.com/dave-irvine/node-hapi-raml/commit/b58228136786f0ff29823d228a20bbcecb65c890

Does this help?

**Comment by vwal** [comment]
Hi @dave-irvine .. I was able to build it, and your example looks very good. I'll play with it and follow up in a few days.

**Comment by vwal** [comment]
Here's some feedback/observations..
    
1. devDeps don't get automatically installed when installing with npm, had to run `npm install` in hapi-raml dir to get them to install<br /><br />Build command is: 
 `"build": "babel src --out-dir lib"`
in the npm installed version, and: 
 `"build": "./node_modules/.bin/babel src --out-dir lib"`
in the Github-cloned version; hence babel & babel-cli must be globally installed with the npm installed version.

2. npm build would not work; had to execute:
`babel src --out-dir lib`
.. for lib to build with the npm installed version.

3. with hapi-raml configured as a module, moved simple.js, simple.raml, and controllers to the project root, installed hapi, then set:<br /><br />```
var Hapi = require('hapi');
var HapiRaml = require('hapi-raml');
```<br /><br />Then ran:
`node ./simple.js`<br /><br />[Error: Cannot add a route without any connections]

4. Added a connection:<br /><br />```server.connection({
    host: 'localhost',
    port: 8000
});```<br /><br />Then ran:
`node ./simple.js`<br /><br />[Error: Unknown authentication strategy: null in path: /simple]

5. added a simple auth:

```
server.register(require('hapi-auth-cookie'), function (err) {
  server.auth.strategy('base', 'cookie', {
    password: 'supersecretpassword', // cookie secret
    cookie: 'app-cookie', // Cookie name
    ttl: 24 * 60 * 60 * 1000 // Set session to 1 day
  });
});
```

But how do I add this as the auth strategy for the route in RAML?<br /><br />Thanks!

**Comment by dave-irvine** [comment]
Hi @vwal,

That's quite a laundry list of issues! None of which I get :( I'm going to guess that this is because we are running different versions of some things. Your first post said you were using node 4.1.1. Is this still the case? I'll install this now.

Can you also give me the version of npm and hapi that you are using?

**Comment by vwal** [comment]
Hi @dave-irvine,

I tried with node 4.2.2 and 5.0.0 (I'm using `n` so it's easy to switch between the different versions). And the latest hapi (whatever comes from npm currently, I think it's 11.1.0). Running on Ubuntu 12.04. With node 4.2.2 npm is at 2.14.7, and with 5.0.0 it's at 3.3.6.

My goal with this experiment is that it would be possible to design an API using [Restlet Studio](http://studio.restlet.com/), or Mulesoft's [Anypoint RAML editor](https://anypoint.mulesoft.com/accounts/#/signin), then just pull the RAML in, and write the corresponding controllers for it.

**Comment by dave-irvine** [comment]
Hi @vwal,

Ok I think I've solved 1 & 2 by just bundling a built version, so if you could try the latest package from npm that would be great.

I'll try 3 now and see how I get on.

**Comment by dave-irvine** [comment]
Hi @vwal,

Ok on 3 you are quite right, Hapi does throw an error! I think this was just a problem in my documentation, very sorry.

I've pushed new examples to github but I haven't published to npm yet.

Onto 4! This looks like a bug I've introduced into the library itself rather than the documentation so this might be harder to fix.

For 5, take a look at my test file: https://github.com/dave-irvine/node-hapi-raml/blob/master/test/authTest.raml

This should show you how to add a strategy to a route. I'll add proper documentation for this after I fix 4.

**Comment by dave-irvine** [comment]
Hi @vwal,

Ok, 1.6.2 should fix 3 & 4.

Please install and let me know how you get on.

**Comment by dave-irvine** [comment]
Hi @vwal,

1.6.3 contains an example for basic authentication.

**Comment by vwal** [comment]
Hi @dave-irvine, 

It seems to be working now! Thanks for the quick fixes. `npm` install seems to work ok now, `/lib` gets created, and the simple.js hooks ups the /simple route.  I'll look at your test files for further clues; I started with hapi very recently having mostly used Express previously, so I'll have a better grasp on the controller structure after writing few test apps. I'll follow up once I get to functional use of this module, and have better understanding on its operation. :-)

**Comment by dave-irvine** [comment]
Closing for now, re-open or make a new issue if you have any further questions, thanks!
