### ISSUE TITLE
RAML 1.0

### ISSUE THREAD

**Issue by YvanDaSilva** [dave-irvine/node-hapi-raml#2]
Hello,

I was looking into your repository and found that you were using raml parser. They made another one which support raml 1.0.

Are you planning on updating this repo to support raml 1.0 and if so when?
From your point of view what is the estimated effort?

Best regards

**Comment by dave-irvine** [comment]
Hi @YvanDaSilva,

It looks like they haven't published the new parser (https://github.com/raml-org/raml-js-parser-2) to npm yet, once they have done this I will start to look into it.

I don't think it would take much effort to add the support.

**Comment by YvanDaSilva** [comment]
@dave-irvine Thank you for the information :)

**Comment by dave-irvine** [comment]
We'll track https://github.com/raml-org/raml-js-parser-2/issues/8 and see when that resolves.

**Comment by sichvoge** [comment]
The NPM module is actually out already. https://www.npmjs.com/package/raml-1-parser

**Comment by dave-irvine** [comment]
@YvanDaSilva I've hopefully resolved this in the latest release.

https://github.com/dave-irvine/node-hapi-raml/releases/tag/v4.0.0

All my tests pass, but I haven't had a chance to actually use it yes, so it might not work at all.

Feel free to re-open if I've broken everything.

**Comment by sichvoge** [comment]
you could check [this example](https://github.com/raml-org/raml-examples/tree/master/others/world-music-api) that contains 95% of everything RAML 1.0 offers. Maybe it helps to validate your update.

**Comment by dave-irvine** [comment]
Ah, cool, thanks.

**Comment by YvanDaSilva** [comment]
@dave-irvine Awesome ! Thank you very much !
